### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no unicorn_java in java.library.path

### ISSUE THREAD

**Issue by wyu0hop** [zhkl0228/unidbg#23] opened 2019-06-17 09:58 UTC
![image](https://user-images.githubusercontent.com/15089908/59595980-6c68b980-9129-11e9-83c2-d2f4594599ed.png)
看到之前的issue也有一样的报错，我现在用的是最新版

**Comment by linxiaozhi** [comment] 2019-06-17 13:32
Duplicate of #2

**Closed** 2019-07-10 05:31 UTC
